const CartTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  CLEAR_CART: 'CLEAR_CART',
  GET_SHIPPING_PRICE_START: 'GET_SHIPPING_PRICE_START',
  GET_SHIPPING_PRICE_SUCCESS: 'GET_SHIPPING_PRICE_SUCCESS',
  GET_SHIPPING_PRICE_FAIL: 'GET_SHIPPING_PRICE_FAIL',
};

export default CartTypes;
